FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./ /app/

RUN pip3 install -r requirements.txt

RUN ["chmod", "+x", "/app/streamlit-entrypoint.sh"]